### ISSUE TITLE
Keycast is sometimes stopped because error is thrown in pre-command-hook

### ISSUE THREAD

**Issue by yantar92** [ir33k/tb-keycast#5]
When I run a lambda function from inside helm, I can reliably "freeze" the keycast indicator. It happens because `tb-keycast--update` throws and error and Emacs automatically removes it from command hooks.

The error is the following

    (wrong-type-argument symbolp (lambda nil (interactive) (helm-select-nth-action 1)))

**Comment by ir33k** [comment]
Thanks I will look into that.  I did notice once that `tb-keycast--update` was removed from `pre-command-hook` hook but I wasn't able to reproduce that.
